### ISSUE TITLE
error when downloading later package on windows 10 R version 3.5

### ISSUE THREAD

**Issue by yeb-skp** [r-lib/later#101]
Hello,
I am trying to use electron by following the https://github.com/ColumbusCollaboratory/electron-quick-start tutorial. The fact is that when I write npm start, I have the problem Error in LoadNamespace (j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck=vI[[j]]): there is no package called "later". I have checked and later is yet installed. However when I try to install later from github I have the following error. 
![image](https://user-images.githubusercontent.com/54170716/63503086-1f111b80-c4cf-11e9-9220-5b2117586d2b.png)
Do you have any idea how I can fix this problem ?
Best regards, 
Yanis

**Comment by wch** [comment]
It sounds like you need to install a compiler toolchain on your system.
For issues like this, please use https://community.rstudio.com/ or https://stackoverflow.com/.
