### ISSUE TITLE
 Error in execCallbacks(timeoutSecs, all, loop$id) :    Evaluation error: unused argument (0)

### ISSUE THREAD

**Issue by dselivanov** [r-lib/later#125]
Any hints what can cause this? The callback I pass to `later` actually called and then I such traceback:

> Error in execCallbacks(timeoutSecs, all, loop$id) : 
  Evaluation error: unused argument (0). 
> 4.
> stop(structure(list(message = "Evaluation error: unused argument (0).", 
    call = execCallbacks(timeoutSecs, all, loop$id), cppstack = structure(list(
        file = "", line = -1L, stack = c("1   later.so                            0x000000010dbcd1df _ZN4Rcpp9exceptionC2EPKcb + 207", 
        "2   later.so                            0x000000010dbd0e3e _ZNK8Callback14invoke_wrappedEv + 590",  ... 
> 3.
execCallbacks(timeoutSecs, all, loop$id) 
> 2.
later::run_now(timeoutSecs = 0.1, all = FALSE, loop = loop) at NsqConsumer.R#85
> 1.
consumer$start(10)

**Comment by dselivanov** [comment]
Ah, sorry that was a bug in my code. But error from `later` made me struggle to understand what happened.

**Comment by wch** [comment]
Hopefully after #108 is addressed, it'll be easier to debug issues like this.
