### ISSUE TITLE
canonical way to remove a later'd func?

### ISSUE THREAD

**Issue by r2evans** [r-lib/later#131]
Perhaps this is abuse of the intent of `later`, but I'm toying with something that repeatedly checks the status of some things in my current running process. If I have a function that self-inserts itself back into the `later` loop, it just keeps going, but at some point I want to stop it. 

```r
myfun <- function() {
  keep_going <- ... # some checks in this process
  if (keep_going) later::later(myfun, 5) else message("I'm out!")
}
```

There are several methods I've toyed with:

- redefine `myfun <- function() {}`, and it just resolves itself (since it re-retrieves the function definition);
- set a global variable that, if missing or some specific value, `keep_going` is forced false; or
- as provided by #85 and #88, `later:::cancel(as.character(later:::list_queue()[[1]]$id), 0)` (assuming the first task and in the global loop).

I don't like reaching in for the `:::` functions, so I feel the third -- though the most immediate -- is not yet stable enough for package support.

Is there a better by-design method of removing a task (whether recurring or just waiting a while) from a loop?

Since there doesn't appear to be a programmatic way for finding a particular task in the queue (we don't know `id`, and in the above case it changes every 5 seconds anyway), so the only remaining comparator is something like

```r
identical(later:::list_queue()[[1]]$callback, myfun)
```

... which seems like I'm trying too hard.

**Comment by wch** [comment]
The `later()` function returns a function which will cancel the scheduled function.

For example:

```R
cancel <- later(function() message("hello"), 3)

# Cancel the scheduled callback
cancel()
```

For example:

```R
keep_going <- TRUE
cancel <- function() NULL

myfun <- function() {
  if (keep_going) {
    message(".")
    cancel <<- later::later(myfun, 1)
  } else {
    message("I'm out!")
    cancel()
  }
}

myfun()

# Wait for it to print out some dots, then make it stop:
keep_going <- FALSE

# Or you can call cancel() directly.
```

Definitely don't use `list_queue` -- it's really only there for debugging.

**Comment by r2evans** [comment]
Sorry for the noise, @wch, I thought I had read the help docs (skipped Value), I see. That makes a lot of sense.

*sigh*

**Comment by r2evans** [comment]
(... and now I understand what `pool:::scheduleTaskRecurring` is doing ... slick namespace control and dealing with ever-changing task ids.)
