### ISSUE TITLE
Re-licensing later

### ISSUE THREAD

**Issue by hadley** [r-lib/later#138]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/later/graphs/contributors). @mingwandroid, would you permit us to re-license later with the MIT license? If so, please comment "I agree" below.

* [ ] [@mingwandroid](https://github.com/r-lib/later/commits?author=mingwandroid)

**Comment by wch** [comment]
FWIW, @mingwandroid's contribution was the following commit: d97c5ebe527218678f40592d313b7beb60055622

And that code was completely replaced when we upgraded to tinycthread 1.2:
https://github.com/r-lib/later/commit/7920cb0570361833d36fad2f9dbb742ba9ef1462#diff-ecadbfd3b5cf6ce757b9d74490dbb6360724bbbc57b45ff5a6e36a06a884392cL133-L134

**Comment by batpigandme** [comment]
Thanks, @wch. Given the code is no longer in there, I went ahead and submitted a PR (#139) to close.
