### ISSUE TITLE
Disabled when forked process is scheduled

### ISSUE THREAD

**Issue by dipterix** [r-lib/later#140]
An example:

``` r
library(future)

# Enable forked process
options(future.fork.enable = TRUE)
plan(multicore, workers = 2)

ff <- function(){
  print(123)
  later::later(ff, 2)
}
ff()

# 2 workers, spawn 3 processes

fs <- replicate(3, {
  future({
    Sys.sleep(3)
  })
})


later::next_op_secs()
#> [1] -15.88667
```

I know forked process is discouraged, but under some situation, forked process can disable `later` from auto-run. 
Is there any suggestions on how should I re-instantiate global loop?

I tried `later:::ensureInitialized()`, but not worked.

**Comment by dipterix** [comment]
I guess this is an issue where the later autorun is shutdown by forked process, because when shutdown fork, later never gets resumed. This could potentially break the packages depending on `later`'s auto-run feature because anyone can create pthreads using packages like `parallel`, `future`, or `multicore` and potentially disable the auto-run.

I found [this trick](https://github.com/fstpackage/fstcore/blob/b52c4bcc730bc606827bcc3f3bb5472efa26d472/src/openmp.cpp#L79-L87) used by `fst` to detect if forked process is spawned to avoid OpenMP from running. I was wondering how hard it will be to disable auto-run when a pthread is created?

**Comment by wch** [comment]
If I had to guess, I think that it's probably related to the file descriptors and input handler stuff in https://github.com/r-lib/later/blob/master/src/later_posix.cpp.
