### ISSUE TITLE
cpp11 support

### ISSUE THREAD

**Issue by nx10** [r-lib/later#143]
I am currently migrating a package from `Rcpp` to [`cpp11`](https://github.com/r-lib/cpp11/) and was wondering if `cpp11` support was planned for `later`?

I am only including `later` from C++ and it seems `Rcpp` is only used for including `/Rinternals.h`.
I was able to work around that by creating a file with the name `/Rcpp.h` which looks like this:

```c++
#pragma once
#import <cpp11/R.hpp>
``` 

this seems to work without issue so far, but is of course a bit "hacky".
I know `Rcpp` is used in the R interface, but a compiler flag similar to this would be great:

```c++
// later.h
// ...
#ifdnef LATER_CPP11
#include <Rcpp.h>
#else
#include <cpp11/R.h>
#endif
// ...
```

Alternatively the R headers could be included without Rcpp:

```c++
#define R_NO_REMAP
#define STRICT_R_HEADERS
#include "Rinternals.h"
```

**Comment by wch** [comment]
Yes, we're planning on making `later` work with packages that don't want to include Rcpp.
