### ISSUE TITLE
Stop later function 

### ISSUE THREAD

**Issue by cedlfc44** [r-lib/later#146]
Hi:
How can i stop later loop, because i need to save some variables that i produce inside loop every hour for example.
My example code is below.
Thanks for your help
`saveZ<-c()
library(later)
print_time = function(interval = 10) {
  Z<-timestamp()
  saveZ<-rbind(saveZ, Z)
  later::later(print_time, interval)
}
print_time()`

**Comment by wch** [comment]
I'm not sure exactly what you're doing, but I think you might want something like this:

```R
saveZ <- c()
library(later)

cancel <- NULL
print_time <- function(interval = 1) {
  Z <- timestamp()
  saveZ <<- c(saveZ, Z)
  cancel <<- later::later(print_time, interval)
}

print_time()



# To stop, call cancel()
cancel()
```

`later()` returns a function which will cancel the scheduled callback. I used `<<-` to assign it to a scope outside of the `print_time` function. Calling `cancel()` at any time will stop this from running.

Similarly, the `saveZ` needed to be assigned with `<<-`.
