### ISSUE TITLE
Later error messages refer to C++ exception even for pure R callbacks

### ISSUE THREAD

**Issue by shikokuchuo** [r-lib/later#197]
It seems there's still some cleanup required after fixing #191.

The error message output for a pure R error now shows:
```r
later::later(function() stop("oops"))
#> Error in (function ()  : oops
#> later: c++ exception (unknown reason) occurred while executing callback.
```

Previously (before #191) it showed:
```r
later::later(function() stop("oops"))
#> Error in (function ()  : oops
#> later: exception occurred while executing callback: 
#> invoke_wrapped: throwing std::runtime_error
```
So it wasn't correct either with the 'throwing std::runtime_error' message, but the reference to a C++ exception remains misleading.

This is also due to Rcpp using unwind protect by default, so that by the time it gets to our try/catch block in `later`, the exception has been re-thrown by Rcpp and is no longer the original type.

**Comment by jcheng5** [comment]
Ah, thanks. All my testing was testing error handling from `later::run_now()`, not letting the async handler do it.
