### ISSUE TITLE
Error: function 'execLaterFdNative' not provided by package 'later'

### ISSUE THREAD

**Issue by jcheng5** [r-lib/later#203]
**NOTICE:** If you're seeing this error, `install.packages("later")` and restarting R should fix it. If not, please leave a comment including `packageVersion("later")`

---

This error is happening when a copy of a `LinkingTo: later` package (like httpuv or promises) is installed that was built against later 1.4.0, but the version of later that's actually installed is 1.3.1 or earlier.

This is not academic; it happens for many deployed Shiny apps if they are installing binary packages from CRAN or Posit Package Manager.

For example:

1. Last week you took a snapshot of your app to create a [manifest.json](https://docs.posit.co/connect-cloud/how-to/r/dependencies.html) which contains package names and version numbers. Among the entries are `httpuv 1.6.15` and `later 1.3.1`. All is well.
2. Now you've updated your app logic so you redeploy. The container or whatever is rebuilt. The manifest.json hasn't changed, so httpuv 1.6.15 and later 1.3.1 are installed. But now, httpuv 1.6.15 has been rebuilt against the newest later.
3. When httpuv goes to load, you get the above error; the `inst/include/later.h` is trying to load an RCCallable that doesn't exist.

**Comment by jcheng5** [comment]
Easy local repro steps (using promises instead of httpuv as it's much faster to compile):

```r
install.packages("later")
install.packages("promises", type="source")
devtools::install_version("later", "1.3.1")
```

Then restart R and `library(promises)`.

**Comment by shikokuchuo** [comment]
@jcheng5 I've messaged you on Slack.
