### ISSUE TITLE
 Evaluation error: attempt to apply non-function.

### ISSUE THREAD

**Issue by paul-shannon** [r-lib/later#67]
Thus far I cannot reproduce this in a minimal example.   So instead I offer a brief error report and request guidance.   Maybe this is a known problem?  Or my error can be recognized by sharper eyes than mine?    For what it's worth, I use later(f, delay) successfully at several other points in my shiny app.

Context:

1. shiny 1.1.0, R 3.5.1, later 0.7.3.9000, macos
2. in my server function
3. within observeEvent(input$addTrack, {
4.  myFunc <- function() loadBedGraphTrack(trackName, tbl.dhs)
5. myFunc()  # works
6. later(myFunc, delay=1)   fails
````
Error in execCallbacks(timeoutSecs) : 
  Evaluation error: attempt to apply non-function.
````
Any suggestions?

 - Paul

**Comment by paul-shannon** [comment]
Thanks, @wch.    I think I allowed for that possibility, checked and found it not to be the case.  As a test, here are three versions of ````myFunc````, one which makes the function call, the other two which establish that loadBedGraphTrack is a function, and that it is defined and available.

Any ideas?

````
 myFunc <- function() loadBedGraphTrack(trackName, tbl.dhs)
 myFunc <- function() print(class(loadBedGraphTrack))
 myFunc <- function() print(loadBedGraphTrack)
````
The first (my preferred call) fails with the error message ````attempt to apply non-function````.
The second definition executes w/o error, printing ````"function"```` to the console.
The third succeeds, printing this to the console:
````
function (trackName, tbl, deleteTracksOfSameName = TRUE) 
{
    if (deleteTracksOfSameName) {
        removeTracksByName(trackName)
    }
    message <- list(trackName = trackName, tbl = jsonlite::toJSON(tbl))
    session <- shiny::getDefaultReactiveDomain()
    session$sendCustomMessage("loadBedGraphTrack", message)
}
<bytecode: 0x7fbcd8bc7248>
<environment: namespace:igvShiny>
````

**Comment by wch** [comment]
I'd suggest running `debug(loadBedGraphTrack)` or putting a `browser()` at the top of the function, and then step through the code.

Using `options(shiny.error=recover)` might also help.

**Comment by paul-shannon** [comment]
browser() took me right to the problem, very similar to what you diagnosed in 2014, with a similar remedy:

   https://github.com/rstudio/shiny/issues/669

Thank you!

**Comment by wch** [comment]
Oh, that makes sense if you're using `later()` to call a function that uses the default reactive domain. In general, I'd say that using `later()` in a Shiny app is probably not a good idea. I don't know what you're doing with it, but it's possible that using async would work better for your situation. It also has the benefit of preserving the the default reactive domain.

https://blog.rstudio.com/2018/06/26/shiny-1-1-0/
https://shiny.rstudio.com/articles/async.html

**Comment by paul-shannon** [comment]
My main use is to
   - raise a jquery tab
   - once raised, display a new genome track on that tab's igv canvas

If a promise was returned by shiny's updateTabsetPanel, that _would_ be a better solution than
    later(loadTrack, 1)
    updateTabsetPanel(session, tabsetName, select="igvTab")

It's a boon to know about async in Shiny.   I'll read up!

**Comment by wch** [comment]
Oh, if the goal is to wait 1 second before showing a tab, then async probably won't help for that use case.
