### ISSUE TITLE
Cannot install later on Arch Linux

### ISSUE THREAD

**Issue by tschreibe** [r-lib/later#68]
Hi, I had an error while installing later package on archlinux.

System : Linux NIC-DK02 4.17.11-arch1 #1 SMP PREEMPT Sun Jul 29 10:11:16 UTC 2018 x86_64 GNU/Linux
gcc : 8.2.0

`
g++  -I"/usr/include/R/" -DNDEBUG -pthread -I"/home/thomas/.R/lib/Rcpp/include" -I"/home/thomas/.R/lib/BH/include" -D_FORTIFY_SOURCE=2   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt  -c timestamp_win32.cpp -o timestamp_win32.o
gcc -I"/usr/include/R/" -DNDEBUG -pthread -I"/home/thomas/.R/lib/Rcpp/include" -I"/home/thomas/.R/lib/BH/include" -D_FORTIFY_SOURCE=2   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt  -c tinycthread.c -o tinycthread.o
g++ -shared -L/usr/lib64/R/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o later.so RcppExports.o callback_registry.o init.o later.o later_native.o later_posix.o later_win32.o timer_posix.o timestamp_unix.o timestamp_win32.o tinycthread.o -pthread -L/usr/lib64/R/lib -lR
installing to /home/thomas/.R/lib/later/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
sh : ligne 1 : 16090 Abandon                 (core dumped)'/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/RtmpP4GLjS/file3e97172731e7'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
ERROR: loading failed
`

Here is the sessioninfo:
`> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    tcltk_3.5.1`

**Comment by jcheng5** [comment]
We believe this is fixed on the master branch--please try devtools::install_github("r-lib/later"). Sorry for the inconvenience!
