### ISSUE TITLE
later with Rscript

### ISSUE THREAD

**Issue by sokovalevsky** [r-lib/later#70]
I have a problem with later in `Rscript`.
Without later I get result printed
```
$ Rscript -e 'print("Got here!")'
[1] "Got here!"
$
```
With later code executed in a moment and nothing printed
```
$ Rscript -e 'later::later( function() { print("Got here!") }, 5 )'
$
```

I am on ubuntu 16.04 and R version 3.4.4. And would love to use `later` with RScript to automate my script execution and hope to get an advice on how to do it. Thank you.
Installation log:
```
>devtools::install_github( 'r-lib/later' )
Downloading GitHub repo r-lib/later@master
from URL https://api.github.com/repos/r-lib/later/zipball/master
Installing later
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL '/tmp/RtmpBWNDXU/devtools3be73f35c781/r-lib-later-11bd19f'  \
  --library='/home/stanislav/R/x86_64-pc-linux-gnu-library/3.4'  \
  --install-tests 

* installing *source* package ‘later’ ...
Running configure script
Using CC=gcc -std=gnu99
Using CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g
Using CPPFLAGS=
C11-style threads.h support not detected. Using tinycthread library.
** libs
...
```

**Comment by sokovalevsky** [comment]
Just in case anyone interested I came up with temporary solution which uses `screen` tool and `.Rprofile` file.
Put this into your `.Rprofile` located at `~/`. If it doesn't exist create it.
```
# https://stackoverflow.com/questions/45894892/running-r-via-terminal-in-windows-and-leaving-r-session-open
STARTUP_FILE <- Sys.getenv( 'STARTUP_FILE' )
if( file.exists( STARTUP_FILE ) ) source( STARTUP_FILE )
```
Then from another R you could start your `the_script.R` with `later` using `system` function
```
system( 'screen -dm bash -c "STARTUP_FILE=/path/to/the_script.R R --no-save"' )
```
In case you would want to kill that process later you should put `write( Sys.getpid(), '/path/to/the_script_process.pid' )` at the beginning of `the_script.R`. Just read that `pid` later and execute `system( paste( 'kill -9', pid ) )`

**Comment by schloerke** [comment]
Thank you for the small example!

At the end of your script, add `later::run_now()` with an amount of time you're willing to wait before killing the script. (ex. 30s)

Updated script (mac): 

```bash
~: Rscript -e 'later::later( function() { print("Got here!") }, 5 ); later::run_now(30)'
[1] "Got here!"
```
