### ISSUE TITLE
compilation failed for package ‘later’

### ISSUE THREAD

**Issue by trecakov** [r-lib/later#78]
* installing *source* package ‘later’ ...
** package ‘later’ successfully unpacked and MD5 sums checked
Running configure script
Using CC=gcc -std=gnu99
Using CFLAGS=-g -O2
Using CPPFLAGS=-I/usr/local/include
C11-style threads.h support not detected. Using tinycthread library.
** libs
g++  -I/software/development/Build/R-3.4.0/lib64/R/include -DNDEBUG -pthread -DTHREADS_H_SUPPORT=-1 -I"/software/development/Build/R-3.4.0/lib64/R/library/Rcpp/include" -I"/software/development/Build/R-3.4.0/lib64/R/library/BH/include" -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++  -I/software/development/Build/R-3.4.0/lib64/R/include -DNDEBUG -pthread -DTHREADS_H_SUPPORT=-1 -I"/software/development/Build/R-3.4.0/lib64/R/library/Rcpp/include" -I"/software/development/Build/R-3.4.0/lib64/R/library/BH/include" -I/usr/local/include   -fpic  -g -O2  -c callback_registry.cpp -o callback_registry.o
In file included from callback_registry.h:9:0,
                 from callback_registry.cpp:6:
timestamp.h:18:3: error: ‘boost’ does not name a type
   boost::shared_ptr<const TimestampImpl> p_impl;
   ^
timestamp.h: In member function ‘bool Timestamp::future() const’:
timestamp.h:26:12: error: ‘p_impl’ was not declared in this scope
     return p_impl->future();
            ^
timestamp.h: In member function ‘bool Timestamp::operator<(const Timestamp&) const’:
timestamp.h:31:12: error: ‘p_impl’ was not declared in this scope
     return p_impl->less(other.p_impl.get());
            ^
timestamp.h:31:31: error: ‘const class Timestamp’ has no member named ‘p_impl’
     return p_impl->less(other.p_impl.get());
                               ^
timestamp.h: In member function ‘bool Timestamp::operator>(const Timestamp&) const’:
timestamp.h:34:12: error: ‘p_impl’ was not declared in this scope
     return p_impl->greater(other.p_impl.get());
            ^
timestamp.h:34:34: error: ‘const class Timestamp’ has no member named ‘p_impl’
     return p_impl->greater(other.p_impl.get());
                                  ^
timestamp.h: In member function ‘double Timestamp::diff_secs(const Timestamp&) const’:
timestamp.h:39:12: error: ‘p_impl’ was not declared in this scope
     return p_impl->diff_secs(other.p_impl.get());
            ^
timestamp.h:39:36: error: ‘const class Timestamp’ has no member named ‘p_impl’
     return p_impl->diff_secs(other.p_impl.get());
                                    ^
In file included from callback_registry.h:11:0,
                 from callback_registry.cpp:6:
threadutils.h: At global scope:
threadutils.h:15:15: error: ‘boost’ has not been declared
 class Mutex : boost::noncopyable {
               ^
threadutils.h:15:22: error: expected ‘{’ before ‘noncopyable’
 class Mutex : boost::noncopyable {
                      ^
threadutils.h:15:34: error: invalid type in declaration before ‘{’ token
 class Mutex : boost::noncopyable {
                                  ^
threadutils.h:15:34: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
threadutils.h:16:3: error: expected primary-expression before ‘friend’
   friend class ConditionVariable;
   ^
threadutils.h:16:3: error: expected ‘}’ before ‘friend’
threadutils.h:16:3: error: expected ‘,’ or ‘;’ before ‘friend’
threadutils.h:19:1: error: expected unqualified-id before ‘public’
 public:
 ^
make: *** [callback_registry.o] Error 1
ERROR: compilation failed for package ‘later’
* removing ‘/software/development/Build/R-3.4.0/lib64/R/library/later’

The downloaded source packages are in
	‘/tmp/RtmpGW5RgB/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(c("later")) :
  installation of package ‘later’ had non-zero exit status

I tried installing from CRAN, but that didnt work. Any suggestions?

**Comment by wch** [comment]
Can you try installing from github?

```R
devtools::install_github('r-lib/later')
```

**Comment by trecakov** [comment]
That worked. Thanks
