### ISSUE TITLE
Compile host needs more than 1GB of RAM

### ISSUE THREAD

**Issue by scottmmjackson** [r-lib/later#86]
Build fails with code 137. Interpreting this as an out-of-memory kill because increasing the available RAM in the docker fixes it.

Reproducible on an Ubuntu 14 docker with 1GB of RAM every time, until the amount of RAM was increased. I increased to 4GB, so I'm not sure where between 1-4GB it begins failing.

The file that the compile process crashes on is `later_native.cpp`.

This could be wontfix'd as an unavoidable build requirement, but I'm opening this issue in case changes to the file could make compile less RAM-hungry.

**Comment by wch** [comment]
Closing because this was likely due to `make -j4`.
