### ISSUE TITLE
Staged install fails on R >= 3.6.0

### ISSUE THREAD

**Issue by pat-s** [r-lib/later#93]
When doing `install.packages("later")` on R >= 3.6.0, I see

```r
** testing if installed package can be loaded from temporary location
file: /usr/lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/libpng-1.6.34-yln6jrurlov53nqxggncgcev5pynwekg/lib/libpng16.so.16)
Error in slibs[are_shared] : invalid subscript type 'list
```

The problem is solved when setting `Sys.setenv("R_INSTALL_STAGED"=FALSE)`.

Possibly related: http://r.789695.n4.nabble.com/Possible-bug-when-finding-shared-libraries-during-staged-installation-td4757203.html

- OS: CentOS7
- R installed from source

**Comment by wch** [comment]
I can't say for sure, but I suspect it has something to do with the use of spack on your system. The later package doesn't make use of libpng or zlib.

**Comment by pat-s** [comment]
Might be true that Spack is involved here.
However, the only thing I've changed is the R version (and later the env var).
I tried checking in the R changelog what might have changed related to libpng and zlib in R >= 3.6.0 but could not find anything helpful.

_later_ might not be the only package affected by this but the first I fell over.

Feel free to close as it is not really clear who the bad guy is in this case. But maybe other people will come across the same problem and find the discussion here.

**Comment by wch** [comment]
My guess is that there's some interaction between spack and R's staged installation, which was new in R 3.6.0. Does the problem happen with other packages that have compiled code?

I'll leave this open for now to track the issue.

**Comment by pat-s** [comment]
> Does the problem happen with other packages that have compiled code?

Sorry for not replying to this one.
I haven't tried others at this time back then and recently did no installs. 

If I face problems in the future, I'll report them here including possible solutions.
